apiVersion: v1
data:
  version-manifest.yml: |
    applications:
{{- range $key, $value := .Values.versions}}
    - application: {{ $key }}
      version: {{ $value }}
{{- end }}
kind: ConfigMap
metadata:
  name: version-cm
