---
{{- if and (not .Values.development) (.Values.mongodb.persistent) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.name }}-mongodb"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
{{- end }}
