{{- if .Values.development }}
apiVersion: v1
kind: Secret
metadata:
  name: lodestar-backend-configuration
type: Opaque
stringData:
  LODESTAR_GITLAB_API_URL: "{{ .Values.lodestarGitlabApiUrl }}"
  JWT_PUBLIC_KEY_LOCATION: "{{ .Values.jwtPublicKeyLocation }}"
  JWT_ISSUER: "{{ .Values.jwtIssuer }}"
  JWT_ENABLE: "{{ .Values.jwtEnable }}"
  WEBHOOK_TOKEN: "{{ .Values.token.webhook }}"
{{- end }}
