apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.name }}
  name: "{{ .Values.name }}-mongodb"
spec:
  ports:
  - name: mongo
    nodePort: 0
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: "{{ .Values.name }}-mongodb"
    deploymentconfig: "{{ .Values.name }}-mongodb"
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}

