apiVersion: v1
kind: Secret
metadata:
  name: omp-backend-configuration
type: Opaque
stringData:
  OMP_GITLAB_API_URL: "{{ .Values.ompGitlabApiUrl }}"
  JWT_PUBKICKEY_LOCATION: "{{ .Values.jwtPublicKeyLocation }}"
  JWT_ISSUER: "{{ .Values.jwtIssuer }}"
  JWT_ENABLE: "{{ .Values.jwtEnable }}"
  DATABASE_SERVICE_NAME: "{{ .Values.mongodbServiceName }}"
  MONGODB_USER: "{{ .Values.mongodbUser }}"
  MONGODB_PASSWORD: "{{ .Values.mongodbPassword }}"
  MONGODB_DATABASE: "{{ .Values.mongodbDatabase }}"
  MONGODB_ADMIN_PASSWORD: "{{ .Values.mongodbAdminPassword }}"
