apiVersion: v1
kind: Secret
metadata:
  name: omp-backend-configuration
type: Opaque
stringData:
  CACHE_SERVICE: "{{ .Values.cacheService }}"
  OMP_GITLAB_API_URL: "{{ .Values.ompGitlabApiUrl }}"
  JWT_PUBKICKEY_LOCATION: "{{ .Values.jwtPublicKeyLocation }}"
  JWT_ISSUER: "{{ .Values.jwtIssuer }}"
  JWT_ENABLE: "{{ .Values.jwtEnable }}"
