apiVersion: v1
kind: Template
metadata:
  name: "${NAME}"
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: "${OUTPUT_IMAGE_NAME}"
  spec:
    lookupPolicy:
      local: false
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    labels:
      app: "${NAME}"
    name: "${NAME}"
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "${OUTPUT_IMAGE_NAME}:${OUTPUT_IMAGE_TAG}"
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: "${GIT_URL}"
        ref: "${GIT_REF}"
      type: Git
    strategy:
      sourceStrategy:
        from:
          kind: DockerImage
          name: "${BUILDER_IMAGE_NAME}:${BUILDER_IMAGE_TAG}"
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      build: "${NAME}"
      name: "${NAME}-pipeline"
      type: pipeline
      app: "${NAME}"
    name: "${NAME}-pipeline"
  spec:
    nodeSelector: {}
    output: {}
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: "${PIPELINE_CONTEXT_DIR}"
      git:
        ref: "${GIT_REF}"
        uri: "${GIT_URL}"
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
      type: JenkinsPipeline
    triggers:
    - type: ConfigChange
    - type: Bitbucket
      bitbucket:
        secret: "${BITBUCKET_WEBHOOK}"
    - type: Generic
      generic:
        secret: "${GENERIC_WEBHOOK}"
    - type: GitHub
      github:
        secret: "${GITHUB_WEBHOOK}"
    - type: GitLab
      gitlab:
        secret: "${GITLAB_WEBHOOK}"
parameters:
- name: NAME
  description: The name of the resources to be created
  required: true
- name: OUTPUT_IMAGE_NAME
  description: The imagestream to push the image to when it has been built
  required: true
- name: OUTPUT_IMAGE_TAG
  description: The tag to give the image when it has been built
  required: true
- name: BUILDER_IMAGE_NAME
  description: The image to use for the s2i build
  required: true
- name: BUILDER_IMAGE_TAG
  description: The tag of the builder image to use
  required: true
- name: GIT_URL
  description: The Git URL of the project containing the OMP API
  required: true
- name: GIT_REF
  description: The git reference to pull for building the app
  required: true
- name: PIPELINE_CONTEXT_DIR
  displayName: Git Context Directory for Jenkinsfile
  description: Set this to the directory where the Jenkinsfile is if not using the
    default root directory
- name: BITBUCKET_WEBHOOK
  displayName: Bitbucket Webook
  description: OCP secret string to configure a Bitbucket webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GENERIC_WEBHOOK
  displayName: Generic Webook
  description: OCP secret string to configure a Generic webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GITHUB_WEBHOOK
  displayName: Github Webook
  description: OCP secret string to configure a Github webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: GITLAB_WEBHOOK
  displayName: Gitlab Webook
  description: OCP secret string to configure a Gitlab webhook
  generate: expression
  from: "[a-zA-Z0-9]{20}"
- name: PIPELINE_SOURCE_SECRET
  displayName: Secret for git repository
  description: The name of the OCP secret that has credentials for the pipeline git
    repository
  value: gitlab-auth