name: Add Tags to Release

on:
  release:
    types: [published]

jobs:
  build-if-needed:
    if: github.repository == 'rht-labs/lodestar-backend'
    runs-on: ubuntu-latest
    steps:
    - name: Check whether we need to build this or not
      id: need_to_build
      run: |
        function image_exists() {
            curl --silent -f -lSL https://quay.io/v1/repositories/${{ github.repository }}/tags/$1 > /dev/null
        }
        if image_exists ${{ github.sha }}; then
            echo "Image exists - not building"
            echo ::set-output name=need_to_build::0
        else 
            echo "Image needs to be built"
            echo ::set-output name=need_to_build::1
        fi
    - uses: actions/checkout@v2
      if: steps.need_to_build.outputs.need_to_build == 1
    - name: Find and Replace Reader Writer
      if: steps.need_to_build.outputs.need_to_build == 1
      shell: bash
      env:
        READER: ${{ secrets.READERS }}
        WRITER: ${{ secrets.WRITERS }}
      run: |
        sed -i '/^quarkus.http.auth.policy.role-reader.roles-allowed/ s/$/,'"$READER"'/' src/main/resources/application.properties
        sed -i '/^quarkus.http.auth.policy.role-writer.roles-allowed/ s/$/,'"$WRITER"'/' src/main/resources/application.properties
    - name: Find and Replace Commit
      if: steps.need_to_build.outputs.need_to_build == 1
      uses: jacobtomlinson/gha-find-replace@0.1.2
      with:
        find: "###GIT_COMMIT###"
        replace: "${{ github.sha }}"
        include: ".s2i"
    - uses: redhat-cop/github-actions/s2i@v2
      if: steps.need_to_build.outputs.need_to_build == 1
      with:
        base: registry.access.redhat.com/ubi8/openjdk-11:1.3
        output_image: "quay.io/${{ github.repository }}:${{ github.sha }}"
        image_push_registry: quay.io
        image_push_username: ${{ secrets.QUAY_USERNAME }}
        image_push_password: ${{ secrets.QUAY_PASSWORD }}

  release:
    runs-on: ubuntu-latest
    needs: build-if-needed
    steps:
    - uses: actions/checkout@v2
    - name: tag with release version
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: ${{ github.repository }}
        image_old_tag: ${{ github.sha }}
        image_new_tag: ${{ github.event.release.tag_name }}
        registry: quay.io
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}
    - name: tag with latest
      uses: tinact/docker.image-retag@1.0.2
      with:
        image_name: ${{ github.repository }}
        image_old_tag: ${{ github.sha }}
        registry: quay.io
        registry_username: ${{ secrets.QUAY_USERNAME }}
        registry_password: ${{ secrets.QUAY_PASSWORD }}
